### ISSUE TITLE
Offline environment 

### ISSUE THREAD

**Issue by luisvega23** [EpicWink/proxpi#33]
## Problem definition

I'm trying to use proxpi in an offline environment: I'm downloading and caching all pip packages I want to move to my offline environment using a proxpi instance in a online one, then I'm moving a tar.gz with all the files to the offline one and mounting it on the proxpi running on it, but then i can't install any package using the offline one.

Maybe I missing some configuration ?  This is how my docker-compose.yaml looks like in my online environment;

```yaml

services:
  proxpi:
    volumes:
      - '/home/ubuntu/proxpi-cache/:/etc/cached/'
    environment:
      - PROXPI_CACHE_DIR=/etc/cached/
    container_name: proxpi-online
    restart: unless-stopped
    ports:
      - '5000:5000'
    image: epicwink/proxpi:latest

```

And this one is for my offline one:

```yaml

services:
  proxpi:
    volumes:
      - '/home/ubuntu/proxpi-cache/:/etc/cached/'
    environment:
      - PROXPI_INDEX_URL=http://localhost:5000/index/
      - PROXPI_CACHE_DIR=/etc/cached/
    container_name: proxpi-online
    restart: unless-stopped
    ports:
      - '5000:5000'
    image: epicwink/proxpi:latest

```

## Current behaviour and workarounds

Can't install the packages in a offline environment after moving the files from one volume to another. I haven't find a workaround yet.

**Comment by EpicWink** [comment]
What exact issue are you having? You're going to have to be more descriptive than:

> i can't install any package using the offline one

What action are you taking which is failing? Is it a `pip install`?

What are the error messages from your action, if any (eg `pip install` output).

What are the error logs from `proxpi`? In your case, you can run `docker compose logs proxpi`.

---

I suspect the issue is actually not one with `proxpi`, but your Docker (Compose) configuration: the re-use of ports and attempting to access a server on the host network.

If your source index server is already running on port 5000, then you can't use that same port for `proxpi`: choose a different port for one of them (the port for `proxpi` is set at the command-line).

You can't access a local server (your source index) from within a Docker container by default. You can enable this with [`network`](https://docs.docker.com/network/drivers/host/) field in the Compose file using the [Host driver](https://docs.docker.com/network/drivers/host/):

```yaml
services:
  proxpi:
    networks: [host]
    ...

networks:
  host:
    driver: host
```

Alternatively, run your source index with the same Docker Compose configuration, and replace `localhost` with the name of the Compose service
