### ISSUE TITLE
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. when add PROXPI_EXTRA_INDEX_URLS

### ISSUE THREAD

**Issue by uxfion** [EpicWink/proxpi#59]
I am currently using Proxpi via Docker, and everything is working great. I appreciate this project a lot! However, I would like to propose a feature that would significantly enhance its usability for deep learning applications.

## Problem definition

Deep learning libraries, particularly those available via pip, often have large installation packages that require considerable download time. For instance, installing PyTorch necessitates specifying different CUDA versions through the --index-url option. This process bypasses the local Proxpi cache server, meaning that these packages are not stored for future use. As a result, each installation requires a fresh download, which can be quite time-consuming.

https://pytorch.org/get-started/locally/

```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118  # cuda11.8
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121  # cuda12.1
pip3 install torch torchvision torchaudio  # cuda12.4
```

## Current behaviour and workarounds

Currently, when using the `--index-url` option with pip to install PyTorch (e.g., for CUDA 11.8, 12.1, or 12.4), the requests are directed to external repositories, and no caching occurs on the Proxpi server. This leads to repeated downloads of the same packages, which is inefficient and frustrating for users who frequently switch between CUDA versions.

## Proposed solution (optional)

I propose the ability to customize the Proxpi index to point to specific CUDA versions of PyTorch while still allowing caching functionality. For example, users could specify the following commands:

```
pip install --index-url http://my-server:9191/cu121/ torch torchvision torchaudio
pip install --index-url http://my-server:9191/cu118/ torch torchvision torchaudio
pip install --index-url http://my-server:9191/cu124/ torch torchvision torchaudio
```

This enhancement would greatly improve the user experience for those who regularly install deep learning packages, reducing download times and making the process much more efficient.

I want to ask if this is possible to achieve, as I really need this functionality to cache a specific index-url🥹😭.

**Comment by uxfion** [comment]
I found that after adding the environment variable, indexing was possible.
```
- PROXPI_EXTRA_INDEX_URLS=https://download.pytorch.org/whl/cu118,https://download.pytorch.org/whl/cu121,https://download.pytorch.org/whl/cu124
```

But another problem has also arisen. When I just installed torch on server A `pip install torch==2.4.1+cu121 torchvision==0.19.1+cu121 torchaudio==2.4.1+cu121`, and then installed it in the same way on server B, an error occurs, as follows:

```
pip install torch==2.4.1+cu121 torchvision==0.19.1+cu121 torchaudio==2.4.1+cu121
Looking in indexes: http://172.25.17.40:9191/index/
Collecting torch==2.4.1+cu121
  Using cached http://172.25.17.40:9191/index/torch/torch-2.4.1%2Bcu121-cp310-cp310-linux_x86_64.whl
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    torch==2.4.1+cu121 from http://172.25.17.40:9191/index/torch/torch-2.4.1%2Bcu121-cp310-cp310-linux_x86_64.whl:
        Expected sha256 f3ed9a2b7f8671b2b32a2f036d1b81055eb3ad9b18ba43b705aa34bae4289e1a
             Got        e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

## Reproduction steps
```
services:
  proxpi:
    image: epicwink/proxpi:latest
    container_name: proxpi
    restart: always
    oom_kill_disable: true
    mem_limit: 3072m
    memswap_limit: 3072m
    ports:
      - 9191:5000
    volumes:
      - ./data:/var/cache/proxpi
    environment:
      - TZ=Asia/Shanghai
      - PROXPI_CACHE_DIR=/var/cache/proxpi
      - PROXPI_CACHE_SIZE=1073741824000  # 1000GB
      - PROXPI_EXTRA_INDEX_URLS=https://download.pytorch.org/whl/cu118,https://download.pytorch.org/whl/cu121,https://download.pytorch.org/whl/cu124
      - PROXPI_EXTRA_INDEX_TTLS=1800,1800,1800
```
`docker compose up -d` on cache server.
set up 
```
sudo tee /etc/pip.conf << EOF
[global]
index-url = http://172.25.17.40:9191/index/
# extra-index-url = https://pypi.org/simple
trusted-host = 172.25.17.40
EOF
```
and do `pip install torch==2.4.1+cu121 torchvision==0.19.1+cu121 torchaudio==2.4.1+cu121` on server A. After that do the same command on server B. Error occur.
