### ISSUE TITLE
 pip install  404

### ISSUE THREAD

**Issue by githubliuyang777** [EpicWink/proxpi#62]
A paragraph or two of the bug.

## Reproduction
1. deploy on k8s use yaml:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pypi-deployment
  namespace: pypi
spec:
  selector:
    matchLabels:
      app: pypi
  template:
    metadata:
      labels:
        app: pypi
    spec:
      containers:
      - env:
        - name: PROXPI_INDEX_URL
          value: https://mirrors.aliyun.com/pypi/simple
        - name: PROXPI_EXTRA_INDEX_URLS
          value: https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
        - name: PROXPI_LOGGING_LEVEL
          value: DEBUG
        - name: PROXPI_CACHE_DIR
          value: /opt/pypi-cache
        image: epicwink/proxpi:latest
        imagePullPolicy: IfNotPresent
        name: pypi
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
        volumeMounts:
        - mountPath: /opt/pypi-cache
          name: data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: pypi-cache-data
---
apiVersion: v1
kind: Service
metadata:
  name: pypi-service
  namespace: pypi
spec:
  ports:
  - name: http-port
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: pypi
  sessionAffinity: None
  type: ClusterIP

2. run a pip client container, use command:
python -m pip install pandas -i http://pypi-service.pypi:5000/simple --trusted-host pypi-service.pypi:5000
client log: 
Looking in indexes: http://pypi-service.pypi:5000/simple
ERROR: Could not find a version that satisfies the requirement pandas (from versions: none)
ERROR: No matching distribution found for pandas
proxpi log:
gunicorn.access: 172.25.64.3 "GET /simple/pandas/ HTTP/1.1" 404 207 0ms

3. but use test command in pip client container, its work:
python -m pip install pandas -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

## Expected behaviour
pip install by proxpi works fine

## Actual behaviour
Could not find a version that satisfies the requirement pandas

## Environment
* `proxpi`: *version*
* Environment: *Docker container*
* Python: *3.8.20*
* OS: *Alpine Linux v3.20*
* *Other relevant packages' versions*

**Comment by EpicWink** [comment]
Try adding a trailing forward-slash `/` to each of your index URL environment variable values, ie change

```yaml
- name: PROXPI_INDEX_URL
  value: https://mirrors.aliyun.com/pypi/simple
- name: PROXPI_EXTRA_INDEX_URLS
  value: https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
```

to


```yaml
- name: PROXPI_INDEX_URL
  value: https://mirrors.aliyun.com/pypi/simple/
- name: PROXPI_EXTRA_INDEX_URLS
  value: https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/
```

---

When fetching the files for a package, `proxpi` performs a standard URL-join:

```python
from urllib.parse import urljoin

assert urljoin("https://example.com/spam", "eggs") == "https://example.com/eggs"
assert urljoin("https://example.com/spam/", "eggs") == "https://example.com/spam/eggs"
```
